"""updated tags

Revision ID: b25eebcbcf36
Revises: def39e33cf68
Create Date: 2020-11-24 13:41:20.901779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b25eebcbcf36'
down_revision = 'def39e33cf68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('only_one_tag_per_user', 'tags', ['user_id', 'title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('only_one_tag_per_user', table_name='tags')
    # ### end Alembic commands ###
