"""upgraded notebooks to be unique per user

Revision ID: 8a3e7cb7f4b8
Revises: ca0e80f37f3e
Create Date: 2020-11-24 14:03:05.623391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a3e7cb7f4b8'
down_revision = 'ca0e80f37f3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('only_one_unique_notebook_per_user', 'notebooks', ['user_id', 'title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('only_one_unique_notebook_per_user', table_name='notebooks')
    # ### end Alembic commands ###
